;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        ivy-switch-buffer
        mouse-set-region
        smex
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        end-of-buffer
        package-install
        sanityinc/toggle-delete-other-windows
        ))
